### ISSUE TITLE
Conflict in getx and get_storage package

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/get_storage#11]
get version: **3.4.3**
get_storage version: **1.2.1**

![image](https://user-images.githubusercontent.com/107820/89598715-0f314980-d890-11ea-8e01-b08cf437fad1.png)

**Comment by jonataslaw** [comment]
Thanks for point this, I will update get_storage

**Comment by jonataslaw** [comment]
fix on lastest version
