### ISSUE TITLE
FAILURE: Build failed with an exception.  with get_storage 2.1.0

### ISSUE THREAD

**Issue by dwzrlp** [jonataslaw/get_storage#125]
**For Android:**
../../.pub-cache/hosted/pub.dev/get_storage-2.1.0/lib/src/storage/io.dart:24:15: Error: Method 'clear' cannot be called on 'Map<String, dynamic>?' because it is potentially null.
 - 'Map' is from 'dart:core'.
Try calling using ?. instead.
      ..value.clear()
              ^^^^^
../../.pub-cache/hosted/pub.dev/get_storage-2.1.0/lib/src/storage/io.dart:57:25: Error: Operator '[]' cannot be called on 'Map<String, dynamic>?' because it is potentially null.
 - 'Map' is from 'dart:core'.
    return subject.value[key] as T?;
                        ^
../../.pub-cache/hosted/pub.dev/get_storage-2.1.0/lib/src/storage/io.dart:61:26: Error: Property 'keys' cannot be accessed on 'Map<String, dynamic>?' because it is potentially null.
 - 'Map' is from 'dart:core'.
Try accessing using ?. instead.
    return subject.value.keys as T;
                         ^^^^
../../.pub-cache/hosted/pub.dev/get_storage-2.1.0/lib/src/storage/io.dart:65:26: Error: Property 'values' cannot be accessed on 'Map<String, dynamic>?' because it is potentially null.
 - 'Map' is from 'dart:core'.
Try accessing using ?. instead.
    return subject.value.values as T;
                         ^^^^^^
../../.pub-cache/hosted/pub.dev/get_storage-2.1.0/lib/src/storage/io.dart:77:15: Error: Method 'remove' cannot be called on 'Map<String, dynamic>?' because it is potentially null.
 - 'Map' is from 'dart:core'.
Try calling using ?. instead.
      ..value.remove(key)
              ^^^^^^
../../.pub-cache/hosted/pub.dev/get_storage-2.1.0/lib/src/storage/io.dart:83:14: Error: Operator '[]=' cannot be called on 'Map<String, dynamic>?' because it is potentially null.
 - 'Map' is from 'dart:core'.
      ..value[key] = value
             ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

**For iOS:**

Could not build the precompiled application for the device.
Error (Xcode): ../../.pub-cache/hosted/pub.dev/get_storage-2.1.0/lib/src/storage/io.dart:24:15: Error: Method 'clear' cannot be called on 'Map<String, dynamic>?' because it is potentially null.

**Comment by jonataslaw** [comment]
Could you please to test the version 2.1.1?

**Comment by dwzrlp** [comment]
> Could you please to test the version 2.1.1?

Version 2.1.1 works fine. Thanks
