### ISSUE TITLE
get_storage not working 

### ISSUE THREAD

**Issue by Eng-MohamedGadala** [jonataslaw/get_storage#22]
When I try to run into ios simulator 
![Screen Shot 2020-09-10 at 1 26 37 PM](https://user-images.githubusercontent.com/6634311/92723467-62a02700-f369-11ea-8919-2056d3d86e5e.png)

 get_storage:

**Comment by doxadoxa** [comment]
I've faced same problem with version get_storage 1.3.0 into Android Simulator too.

**Comment by jonataslaw** [comment]
I'm doing an update right now to fix this.

**Comment by Eng-MohamedGadala** [comment]
Everything working now, thanks.
