### ISSUE TITLE
Corruption occurred while in debugger

### ISSUE THREAD

**Issue by travishaagen** [jonataslaw/get_storage#23]
While using the debugger on a simulated iOS device, some kind of corruption occurred and after app restart, the corrupted state continued. I had to do a `flutter clean` and delete the app from the simulated device.

Stacktrace:
```
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'String'
#0      GetStorage._init (package:get_storage/src/storage_impl.dart:47:7)
<asynchronous suspension>
#1      new GetStorage._internal.<anonymous closure> (package:get_storage/src/storage_impl.dart:27:13)
#2      new Future.<anonymous closure> (dart:async/future.dart:175:37)
#3      _rootRun (dart:async/zone.dart:1182:47)
#4      _CustomZone.run (dart:async/zone.dart:1093:19)
#5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#7      _rootRun (dart:async/zone.dart:1190:13)
#8      _CustomZone.run (dart:async/zone.dart:1093:19)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#12 <…>
```

The debugger was set for "break on exception" and was in the `StorageImpl._readFile` method.

Note that I just started using this library, and am only storing a _single_ `String` value.

I do not have any additional information, and cannot reproduce, but it is concerning that the bad state remained after restarting the app. I would rather the storage be erased than have the app unusable.

Versions:
```
flutter: 1.20.3
get: 3.10.2
get_storage: 1.3.1
```

**Comment by rhisiart-cufflink** [comment]
When I come across this type of problem I tend to run the following command to delete all the storage files...

```
find . -name "*.gs" -exec rm {} \;
```

**Comment by invipal** [comment]
I got same error;

`E/flutter ( 7801): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'String'
E/flutter ( 7801): #0      GetStorage._init (package:get_storage/src/storage_impl.dart:47:7)
E/flutter ( 7801): <asynchronous suspension>
E/flutter ( 7801): #1      new GetStorage._internal.<anonymous closure> (package:get_storage/src/storage_impl.dart:27:13)
E/flutter ( 7801): #2      new Future.<anonymous closure> (dart:async/future.dart:175:37)
E/flutter ( 7801): #3      _rootRun (dart:async/zone.dart:1182:47)
E/flutter ( 7801): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 7801): #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 7801): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 7801): #7      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 7801): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 7801): #9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter ( 7801): #10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter ( 7801): #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter ( 7801): #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter ( 7801): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 7801): `

Versions: 

`
flutter: 1.20.3
get: 3.11.1
get_storage: 1.3.1
`
