### ISSUE TITLE
Please add removeKeyListen back

### ISSUE THREAD

**Issue by ghprod** [jonataslaw/get_storage#24]
Hi

Why `removeKeyListen` was removed? 

Since we can use `listenKey`, then we need the ability to remove this listener right?

Thanks

**Comment by jonataslaw** [comment]
Thanks for opening this issue, today there is an API that makes it easier, the function that adds the listener give the one that  remove it, you can do, for example:

```dart
final remove = listenKey('key',(value){
print(value);
});
```

to remove:
`remove();`
or
`remove.call();`


However, I needed to do a break update and insert this into the documentation.
Thanks for advise it

**Comment by ghprod** [comment]
Thanks, @jonataslaw for the answer :+1: 

Close it :100:
