### ISSUE TITLE
Key is available or not 

### ISSUE THREAD

**Issue by rupamking1** [jonataslaw/get_storage#28]
I did not find any thing to check Key is available or not,
how to check Key is available or not ?

**Comment by scris** [comment]
I have the same question, hoping for a fine solution.
Sincerely thanks if someone can help.

**Comment by scris** [comment]
`writeIfNull` might help, I think.

**Comment by scris** [comment]
I believe I've found the true answer, `hasData`.
The author should have mentioned it in the doc, and I'll add that if free of work.

**Comment by rupamking1** [comment]
Okay, Thank You
