### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by stefandevo** [jonataslaw/get_storage#4]
I get following error when running on iOS Simulator:

```
[ios/.symlinks/plugins/path_provider_linux/example] flutter pub get
Running "flutter pub get" in example...                         
Because pathproviderexample depends on path_provider from path which doesn't exist (could not find package path_provider at "../../path_provider"), version solving failed.
pub get failed (66; Because pathproviderexample depends on path_provider from path which doesn't exist (could not find package path_provider at "../../path_provider"), version solving failed.)
```

get_storage: ^1.1.6
Flutter 1.20.0-0.0.pre

android is working OK!

**Comment by jonataslaw** [comment]
Hi Stefan, it seems that strangely Flutter is not downloading the path_provider dependency on iOS, there are several current problems with pana including that it is not being able to analyze packages that use the path provider (any package that stores anything depends on it), and I believe that the solution is to manually add `path_provider` to your `pubspec.yaml`.
If it works for you I will make this reservation in the readme, thanks for letting me know.

**Comment by stefandevo** [comment]
Hi; so I am on DEV channel.
I need to add `path_provider: ^1.6.9` which is not the very latest of `path_provider`.
`1.6.10` introduced Linux support and that seems to be the one that is causing the problems.
