### ISSUE TITLE
Cant read Storage on onInit()

### ISSUE THREAD

**Issue by ingomc** [jonataslaw/get_storage#40]
so i have this simple controller, and in **onInit box.read('citys') is null**, i dont know why, is it a bug, how do i get the value in onInit and assign it to something?

with the getter of my controller, i am able to get the value from storage.

(First time this runs, it should be null, but secondtime it should return the stored value, its there i get it from the getter)

**controller.dart**

```
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';

class TestController extends GetxController {
  final box = GetStorage();
  String get stringtext => box.read('citys') ?? "nux";

  @override
  void onInit() {
    print(box.read('citys')); // returns null ?????
    print('write');
    box.write('citys', 'Hallo!!');
    super.onInit();
  }
}
```

**main.dart**

```
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'controller.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final TestController testController = Get.put(TestController());

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: SimpleBuilder(
            builder: (_) {
              return Text(testController.stringtext);
            },
          ),
        ),
      ),
    );
  }
}
```

**Comment by jonataslaw** [comment]
Initialize GetStorage (read the docs!)

**Comment by ingomc** [comment]
Ok forgot Initialize GetStorage and also getMaterialApp in this Demo .. sry for that... that was the Problem in the Demo, but i didn't forget it in my acutal App, and there it doesnt work with it initialized, so there is probably an error somewhere, im lookin into it, perharps i can find the error or reproduce it somehow.

Sorry for that in the demo, and thank you for the repsonse

**Comment by cwangfr** [comment]
@ingomc 
i have same problem, but i fixed use await GetStorage.init();
"await" is key point
