### ISSUE TITLE
FileSystemException on Windows

### ISSUE THREAD

**Issue by qwert2603** [jonataslaw/get_storage#49]
Hello! Error is thrown on Windows 10.

`[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: lock failed, path = 'C:\Users\win10\Documents/GetStorage.gs'`

* `get_storage: 1.4.0`
* `flutter: 2.0.1`

Error is thrown when calling `GetStorage.wrile(...)` second and next times after app lauched.

**Comment by rupamking1** [comment]
Please fix it

**Comment by StormiFire** [comment]
This issue can be closed!
