### ISSUE TITLE
Error after upgraded getx to 4.0.0-nullsafety.2

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/get_storage#52]
Because get_storage >=1.3.2 depends on get ^3.15.0 and viqcorex depends on get ^4.0.0-nullsafety.2, get_storage >=1.3.2 is forbidden.
So, because viqcorex depends on get_storage ^1.4.0, version solving failed.

**Comment by jonataslaw** [comment]
Closed by https://github.com/jonataslaw/get_storage/pull/51 
Update to GetStorage 2.0
