### ISSUE TITLE
Remove collection: ^1.15.0-nullsafety.4 from dependencies

### ISSUE THREAD

**Issue by prateekmedia** [jonataslaw/get_storage#53]
This dependency was auto added by dart migration tool in the commit https://github.com/jonataslaw/get_storage/blob/2928213dccccf89802e8606b309c2ef6e463bec4/pubspec.yaml#L14

It is not needed by this plugin(I guess), so it needs to be removed.

**Comment by StormiFire** [comment]
This issue can be closed!
