### ISSUE TITLE
The process cannot access the file because another process has locked a portion of the file

### ISSUE THREAD

**Issue by kingrupam** [jonataslaw/get_storage#54]
Flutter Windows:  [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: lock failed, path = 'C:\Users\Rupam\Documents/The_Box.gs' (OS Error: The process cannot access the file because another process has locked a portion of the file.
, errno = 33)

**Comment by StormiFire** [comment]
This issue can be closed!
