### ISSUE TITLE
Request get_storage for  flutter web 

### ISSUE THREAD

**Issue by SureshKumar311** [jonataslaw/get_storage#66]
request get_storage for  flutter web

**Comment by jonataslaw** [comment]
It works normally on the web

**Comment by SureshKumar311** [comment]
![Screenshot (76)](https://user-images.githubusercontent.com/51741195/119214494-f1626780-bae4-11eb-8237-9bcfe62430ba.png)
yes now i had tryed it was working correctly but i dont find support in pub.dev website(https://pub.dev/packages/get_storage)

plz update it @jonataslaw 
thank you

**Comment by jonataslaw** [comment]
> ![Screenshot (76)](https://user-images.githubusercontent.com/51741195/119214494-f1626780-bae4-11eb-8237-9bcfe62430ba.png)
> yes now i had tryed it was working correctly but i dont find support in pub.dev website(https://pub.dev/packages/get_storage)
> 
> plz update it @jonataslaw
> thank you

This is a pana analysis error (from pub.dev), unfortunately I have nothing to do but wait for them to fix it
