### ISSUE TITLE
Persist ThemeMode with Get Storage

### ISSUE THREAD

**Issue by TJMusiitwa** [jonataslaw/get_storage#7]
I recall being able to persist a theme with HiveDb that this package is inspired on.
I am able to change the theme for my app but I seem to be finding issues in saving the theme to Get Storage.
Below is the current implementation for a RadioListTile I have set up to change the theme:

```dart
RadioListTile(
                    title: Text('Dark'),
                     value: ThemeMode.dark,
                    groupValue: _themeMode,
                    onChanged: (value) {
                           Get.changeThemeMode(ThemeMode.dark);
                           GetStorage().write('appTheme', ThemeMode.dark.index);
                          print(value.toString()); // ThemeMode.dark
                          print(ThemeMode.dark.index); // 2
                                },
                              ),
```

However it seems to return an error as I can neither write the index value which as an int or the value as a string to then persist which can be read in the GetMaterialApp under the theme to load on startup

Any advice,thanks

**Comment by mdb2301** [comment]
Try writing something like isDark in the storage.
