### ISSUE TITLE
Tests breaking due to path provider on GetStorage.init()

### ISSUE THREAD

**Issue by romater0** [jonataslaw/get_storage#70]
I'm getting this error when I call GetStorage.init()

`Failed to load "/test/app/utils/database_test.dart": MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
GetStorage._init
package:get_storage/src/storage_impl.dart:47
===== asynchronous gap ===========================
new GetStorage._internal.<fn>
package:get_storage/src/storage_impl.dart:28
===== asynchronous gap ===========================
main
test/…/utils/database_test.dart:16
===== asynchronous gap ===========================
/var/folders/tb/1s9dn9sd7xz414ft8llkr7dc0000gn/T/flutter_tools.CrFDe3/flutter_test_listener.4A6vdQ/listener.dart 19:3  _testMain
`

checking previous issues of the same it was fixed but it's still surfacing

**Comment by sheheryarkhan501** [comment]
I am also getting this suddenly. Tried so many things but nothing is fixing it. Please anyone could help?

**Comment by sheheryarkhan501** [comment]
I have spotted my problem. I added mediation so it was causing it. Facebook and unity. For now I have removed it. Need to recheck everything again so that I don't do any step wrong.

**Comment by jonataslaw** [comment]
You need mock path_provider 
https://github.com/jonataslaw/get_storage/blob/master/test/getstorage_test.dart
