### ISSUE TITLE
app freezes on the splash screen in release mode

### ISSUE THREAD

**Issue by webeasystep** [jonataslaw/get_storage#97]
after coule of days I figure I have an issue using get_storage ,
the app work well until I signin , this because I save the login data using get_storage , the splash screen freezes after opening and closing the app multiple times 
this only happen in the release mode flutter 2.10.2.
tested on real device 

### the main.dart
`import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';
import 'package:talab/helpers/translation/LocalizationService.dart';
import 'package:talab/helpers/constant_helper.dart';
import 'package:talab/helpers/binging_helper.dart';
import 'modules/settings/controllers/settings_controller.dart';
import 'modules/users/controllers/login_controller.dart';
import 'modules/users/services/auth_service.dart';

 initServices() async {
  Get.log('starting services ...');
  await GetStorage.init();
  await Get.putAsync(() => AuthService().init());
  Get.put<SettingsController>(SettingsController(),permanent: true).init();
  Get.put<LoginController>(LoginController()).init();
  Get.log('All services started...');
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
    statusBarColor: Colors.transparent, // transparent status bar
  ));
  await initServices();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  const MyApp();

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        hideKeyboard(context);
      },
      child: GetMaterialApp(
        initialRoute: AppPages.INITIAL,
        getPages: AppPages.routes,
        enableLog: true,
        debugShowCheckedModeBanner: false,
        title: Config.AppName,
        theme: AppThemes.appTheme,
        locale: LocalizationService.locale,
        fallbackLocale: LocalizationService.fallbackLocale,
        translations: LocalizationService(),
      ),
    );
  }
  void hideKeyboard(BuildContext context) {
    FocusScopeNode currentFocus = FocusScope.of(context);
    if (!currentFocus.hasPrimaryFocus && currentFocus.focusedChild != null) {
      FocusManager.instance.primaryFocus.unfocus();
    }
  }
}
`

### the authService.dart

`import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';
import '../models/user.dart';

class AuthService extends GetxService {
  final user = User().obs;
  GetStorage _box;

  AuthService() {
    _box = new GetStorage();
  }

  Future<AuthService> init() async {
    user.listen((User _user) {
      _box.write('current_user', _user.toJson());
    });
    await getCurrentUser();
    return this;
  }

Future getCurrentUser() async {
   //this.removeCurrentUser();
    if (user.value.auth == null && _box.hasData('current_user')) {
      var map1 = await _box.read('current_user');
      map1.update('status', (value) => value.toString());
      user.value = User.fromJson(map1);
      user.value.auth = true;
    } else {
      user.value.auth = false;
    }
    print(user.value);
  }

  Future removeCurrentUser() async {
    user.value = new User();
    await _box.remove('current_user');
  }
  bool get isAuth => user.value.auth ?? false;

  //String get apiToken => (user.value.auth ?? false) ? user.value.apiToken : '';
}
`

**Comment by MaddinMade** [comment]
@webeasystep 
I don't use this package, but also have this problem reading files since Flutter 2.10.x. Have you found a solution or a workaround that is not downgrading.

**Comment by webeasystep** [comment]
Sure
Downgrade to 2.8.1
